## National Basketball Association Most Valuable Player Machine Learning Project

Dataset From: https://www.kaggle.com/datasets/robertsunderhaft/nba-player-season-statistics-with-mvp-win-share?resource=download

In [32]:
import tensorflow as tf
import pandas as pd
import numpy as np
import sklearn as skl

### Data Preprocessing and Feature Selection

In [27]:
#Import Data

df = pd.read_csv("mvp-data.csv",header=0,index_col=False)
xtest = pd.read_csv("2023-mvp-candidates.csv")

df.head()

,season,player,pos,age,team_id,g,gs,mp_per_g,fg_per_g,fga_per_g,...,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp,award_share
0,1982,Kareem Abdul-Jabbar,5,34,LAL,76,76,35.2,9.9,17.1,...,25.6,6.9,3.9,10.7,0.192,3.8,1.2,5.0,4.7,0.045
1,1982,Alvan Adams,5,27,PHO,79,75,30.3,6.4,13.0,...,22.8,2.5,4.7,7.2,0.144,1.4,2.2,3.6,3.4,0.000
2,1982,Mark Aguirre,3,22,DAL,51,20,28.8,7.5,16.1,...,29.8,1.0,0.8,1.9,0.061,2.3,-1.6,0.7,1.0,0.000
3,1982,Danny Ainge,2,22,BOS,53,1,10.6,1.5,4.2,...,21.5,-0.3,0.8,0.5,0.042,-3.7,1.0,-2.7,-0.1,0.000
4,1982,Tiny Archibald,1,33,BOS,68,51,31.9,4.5,9.6,...,17.9,3.4,1.8,5.2,0.115,1.4,-1.3,0.1,1.1,0.000

In [28]:
# Remove index, season columns, Team ID, Remove Player Name column

df = df.drop(['season','team_id','player', 'g', 'gs', 'mp'],axis=1)
xtest = xtest.drop(['season','team_id','player', 'g', 'gs', 'mp'],axis=1)
df.head()

,pos,age,mp_per_g,fg_per_g,fga_per_g,fg_pct,fg3_per_g,fg3a_per_g,fg3_pct,fg2_per_g,...,usg_pct,ows,dws,ws,ws_per_48,obpm,dbpm,bpm,vorp,award_share
0,5,34,35.2,9.9,17.1,0.579,0.0,0.0,0.000,9.9,...,25.6,6.9,3.9,10.7,0.192,3.8,1.2,5.0,4.7,0.045
1,5,27,30.3,6.4,13.0,0.494,0.0,0.0,0.000,6.4,...,22.8,2.5,4.7,7.2,0.144,1.4,2.2,3.6,3.4,0.000
2,3,22,28.8,7.5,16.1,0.465,0.5,1.4,0.352,7.0,...,29.8,1.0,0.8,1.9,0.061,2.3,-1.6,0.7,1.0,0.000
3,2,22,10.6,1.5,4.2,0.357,0.1,0.3,0.294,1.4,...,21.5,-0.3,0.8,0.5,0.042,-3.7,1.0,-2.7,-0.1,0.000
4,1,33,31.9,4.5,9.6,0.472,0.1,0.2,0.375,4.4,...,17.9,3.4,1.8,5.2,0.115,1.4,-1.3,0.1,1.1,0.000

In [35]:
#Split Original Dataset into Input and Output DataFrames
ytrain =df['award_share']
xtrain = df.drop(['award_share'], axis=1)

#Fill NaN values with 0
xtrain = xtrain.fillna(0)

In [36]:
# Check Dimensions
ytrain.shape, xtrain.shape, xtest.shape

((17697,), (17697, 45), (5, 45))

In [ ]:
#TODO: If we use TensorFlow, we need to have the data arrays as NumPy Arrays. Conversion can go here.

#Convert data into NumPy Arrays

#xtrain.reset_index()
#xtest.reset_index()
#ytrain.reset_index()

#xtrain = xtrain.to_numpy()
#xtest = xtest.to_numpy()
#ytrain = ytrain.to_numpy()

### Neural Network Application